"""
RADIUS Protocol Constants
"""

# Packet Codes
ACCESS_REQUEST = 1
ACCESS_ACCEPT = 2
ACCESS_REJECT = 3
ACCOUNTING_REQUEST = 4
ACCOUNTING_RESPONSE = 5
ACCESS_CHALLENGE = 11

# Common Attribute Types
ATTR_USER_NAME = 1
ATTR_USER_PASSWORD = 2
ATTR_CHAP_PASSWORD = 3
ATTR_NAS_IP_ADDRESS = 4
ATTR_NAS_PORT = 5
ATTR_SERVICE_TYPE = 6
ATTR_REPLY_MESSAGE = 18
ATTR_SESSION_TIMEOUT = 27
ATTR_IDLE_TIMEOUT = 28
ATTR_ACCT_SESSION_ID = 44

# Service Types
SERVICE_LOGIN = 1
SERVICE_FRAMED = 2
SERVICE_ADMINISTRATIVE = 6

# Default Ports
DEFAULT_AUTH_PORT = 1812
DEFAULT_ACCT_PORT = 1813
