name: 'Setup Python and Poetry'
description: 'Setup Python 3.13 and Poetry with caching'
outputs:
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "poetry>=1.8"

    - name: Cache Poetry / venv
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-py313-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-py313-poetry-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
        poetry install --with dev