"""Configuration constants (section names, environment keys, immutable identifiers)."""

SECTION_SERVER = "server"
SECTION_AUTH = "auth"
SECTION_LDAP = "ldap"
SECTION_DATABASE = "database"
SECTION_SECURITY = "security"
SECTION_WEBHOOKS = "webhooks"
SECTION_LOGGING = "logging"
SECTION_SYSLOG = "syslog"
SECTION_COMMAND_AUTHORIZATION = "command_authorization"
SECTION_BACKUP = "backup"
SECTION_ADMIN = "admin"
SECTION_DEVICES = "devices"
SECTION_RADIUS = "radius"
SECTION_MONITORING = "monitoring"
SECTION_PROXY_PROTOCOL = "proxy_protocol"
SECTION_RADIUS_AUTH = "radius_auth"
SECTION_MFA = "mfa"
SECTION_OPENID = "openid"

ENV_PREFIX = "TACACS_"

ENV_ADMIN_PASSWORD_HASH = "ADMIN_PASSWORD_HASH" # nosec
ENV_LDAP_BIND_PASSWORD = "LDAP_BIND_PASSWORD" # nosec
ENV_OKTA_CLIENT_ID = "OKTA_CLIENT_ID"
ENV_OKTA_CLIENT_SECRET = "OKTA_CLIENT_SECRET" # nosec
ENV_OKTA_PRIVATE_KEY = "OKTA_PRIVATE_KEY" # nosec
ENV_OKTA_PRIVATE_KEY_ID = "OKTA_PRIVATE_KEY_ID"
ENV_BACKUP_ENCRYPTION_PASSPHRASE = "BACKUP_ENCRYPTION_PASSPHRASE" # nosec
ENV_RADIUS_AUTH_SECRET = "RADIUS_AUTH_SECRET" # nosec
ENV_OPENID_CLIENT_SECRET = "OPENID_CLIENT_SECRET" # nosec
ENV_OPENID_CLIENT_PRIVATE_KEY = "OPENID_CLIENT_PRIVATE_KEY" # nosec
ENV_TACACS_SOURCE_URL = "TACACS_SOURCE_URL"

ENV_TACACS_CONFIG = "TACACS_CONFIG"
ENV_CONFIG_REFRESH_SECONDS = "CONFIG_REFRESH_SECONDS"
ENV_CURRENT_ADMIN_USER = "CURRENT_ADMIN_USER"
ENV_INSTANCE_NAME = "INSTANCE_NAME"
